### ISSUE TITLE
log get spammed when about to quit game

### ISSUE THREAD

**Issue by ezio416** [openplanet-nl/mlhook#10]
If in a map and you click the X at the top to quit the game, MLHook spams the log. Probably not a huge deal but still a bit annoying

![Screenshot 2024-03-11 204909](https://github.com/openplanet-nl/mlhook/assets/37951898/0b0c378c-131f-447a-828a-1eb302d29f79)

**Comment by XertroV** [comment]
Not an MLHook issue -- this is from G++. Will fix.
